# Generated by Django 5.1.2 on 2024-10-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveIntegerField()),
                ('branch', models.CharField(choices=[('CE', 'Civil Engineering'), ('EXTC', 'Electronics and Telecommunication'), ('ME', 'Mechanical Engineering'), ('AI', 'Artificial Intelligence'), ('IT', 'Information Technology')], max_length=5)),
            ],
        ),
    ]
